project:
  type: website

website:
  title: "Blog"
  description: "Operations research and industrial statistics"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/AldoRangel98
      - icon: twitter
        href: https://twitter.com/AldoRangel98
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
comments:
  giscus:
    repo: AldoRangel98/Blog
